# Generated by Django 5.1.5 on 2025-01-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Little_lemon_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Category',
            new_name='category',
        ),
    ]
