# Generated by Django 5.1.5 on 2025-01-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Little_lemon_api', '0002_rename_category_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
